### ISSUE TITLE
Improve performance get username

### ISSUE THREAD

**Issue by rudii1410** [cderianb/minecraft-discord-bot#17]
Command yang ngambil nama (!mc-stats, !mc-history) lama responsenya. kayanya karena perlu request ke discord buat ambil nama by user id.

solusinya mungkin perlu ngecache id dan namanya di memory, bahan bacaan: https://realpython.com/lru-cache-python/

**Comment by vreynaldo** [comment]
Sebenernya ada cara improve perfomancenya tanpa perlu pakai cache. Di postgres ada fitur indexing, kita bsa pasang index di column nama, wdyt?

**Comment by rudii1410** [comment]
closed in favor of #28
